title: "Chris Oung"
author: "Chris Oung"
description: " "
lang: "en"

# Page settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/
hide_title: true             # remove site heading in the header
post_footer: false            # show previous and next links at the end of each post

# Theme settings
dark_theme: false           # use the dark mode as default
dark_header: true          # keep the header dark

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  envelope: "https://mailto:chrisoung23@gmail.com"
  github: "https://github.com/chrisoung"
  rss: "/feed.xml"

# Pagination
show_excerpts: false         # preview articles on the home page
paginate: 8                  # number of articles per page
excerpt_separator: "\n\n\n"  # indicate the end of the excerpt by two blank lines

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins: 
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
