
name: CHRISTOPHER OUNG

author: Chris Oung

description: Technical Writer | Junior Software Developer
footer-links:
  dribbble:
  email: oungc1@uw.edu
  facebook:
  flickr:
  github: chrisoung1
  instagram:
  linkedin: chrisoung1
  pinterest:
  rss: https://chrisoung1.github.io
  twitter: 
  stackoverflow:
  youtube: 
  googleplus: 

url: https://chrisoung1.github.io

baseurl: ""

excerpt_separator: <!--more-->

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM

  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlights'


sass:
  style: :expanded 

theme: minima

plugins:
 - jekyll-sitemap 
 - jekyll-feed


exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
